#Microsoft Security Code Analysis
#https://docs.microsoft.com/en-us/azure/security/develop/security-code-analysis-overview
#https://anglo-data-analytics.atlassian.net/wiki/spaces/DW/pages/1423999202/Credential+Scanning+Results
jobs:
  - job: MsSecurityCodeAnalysis
    timeoutInMinutes: 20
    displayName: MS Security Code Analysis
    pool:
      vmImage: "windows-latest"
    steps:
      - task: CredScan@2
        displayName: Credential Scanner
        inputs:
          toolMajorVersion: "V2"
          outputFormat: "csv"

      - task: PublishSecurityAnalysisLogs@2
        displayName: Publish Security Analysis Logs
        inputs:
          ArtifactName: "CodeAnalysisLogs"
          ArtifactType: "Container"
          AllTools: true
          ToolLogsNotFoundAction: "Standard"

      - task: PostAnalysis@1
        displayName: Analyse Security Logs
        inputs:
          AllTools: false
          BinSkim: false
          CredScan: true
          RoslynAnalyzers: false
          TSLint: false
          ToolLogsNotFoundAction: "Error"